name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Причина сборки"
        required: false
        default: "manual build"
  push:
    branches: [ main ]

env:
  IMAGE_APP: luba30analyst/docker-practice-app
  IMAGE_DB: luba30analyst/docker-practice-app-db
  IMAGE_CLIENT: luba30analyst/docker-practice-app-client
  IMAGE_USERS: luba30analyst/docker-practice-app-users
  IMAGE_VOLUME: luba30analyst/docker-practice-app-volume
  IMAGE_WEB: luba30analyst/docker-practice-app-web
  IMAGE_NGINX: luba30analyst/docker-practice-app-nginx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_WRITE_TOKEN }}

      - name: Build and push app v1
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_APP }}:v1
          build-args: APP_VERSION=v1

      - name: Build and push app v2
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_APP }}:v2
          build-args: APP_VERSION=v2

      - name: Build and push app latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_APP }}:latest
          build-args: APP_VERSION=v2

      - name: Build and push db image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          tags: |
            ${{ env.IMAGE_DB }}:v1
            ${{ env.IMAGE_DB }}:latest

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.client
          push: true
          tags: |
            ${{ env.IMAGE_CLIENT }}:v1
            ${{ env.IMAGE_CLIENT }}:latest
          build-args: APP_VERSION=v1

      - name: Build and push users image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.users
          push: true
          tags: |
            ${{ env.IMAGE_USERS }}:v1
            ${{ env.IMAGE_USERS }}:latest
          build-args: APP_VERSION=v1

      - name: Build and push volume image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.volume
          push: true
          tags: |
            ${{ env.IMAGE_VOLUME }}:v1
            ${{ env.IMAGE_VOLUME }}:latest

      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:v1
            ${{ env.IMAGE_WEB }}:latest
          build-args: APP_VERSION=v1

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: |
            ${{ env.IMAGE_NGINX }}:v1
            ${{ env.IMAGE_NGINX }}:latest
